server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db
      username: root
      password: root
  #admin
  boot:
    admin:
      client:
        url: http://localhost:8080

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb1_
      id-type: auto #主键策略：使用数据库自增策略，默认使用雪花算法
  configuration:
    # 开启MyBatisPlus的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印控制台

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
#        include: health, info
        include: "*"

info:
  author: Nerea
  appName: @project.artifactId@
  version: @project.version@
  company: KiwiES

tools:
  ip:
    cycle: 10
    cycle-reset: false
    model: "detail"
