cartoon:
  cat:
    name: TomK
    age: 3
  mouse:
    name: JerryW
    age: 4

cartoon2:
  cat:
    name: TomK
    age: 5
  mouse:
    name: JerryW
    age: 8

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.task.TaskExecutionAutoConfiguration
#      - org.springframework.boot.autoconfigure.context.LifecycleAutoConfiguration