spring:
  task:
    scheduling:
      pool:
        size: 2 #任务调度线程池大小 默认1
      thread-name-prefix: spring_tasks_  # 调度线程名称前缀 默认 scheduling-
      shutdown:
        await-termination: false #线程池关闭时等待所有任务完成
        await-termination-period: 10s #调度线程关闭前最大的等待时间，确保最后一定关闭
